/**
 * Permission constants — must match exactly the names in the DB.
 * Grouped by module for readability.
 */
export const PERMISSIONS = {
  // BRANDS
  READ_BRANDS:           'READ_BRANDS',
  CREATE_BRANDS:         'CREATE_BRANDS',
  UPDATE_BRANDS:         'UPDATE_BRANDS',
  DELETE_BRANDS:         'DELETE_BRANDS',
  CHANGE_STATUS_BRANDS:  'CHANGE_STATUS_BRANDS',

  // CATEGORIES
  READ_CATEGORIES:           'READ_CATEGORIES',
  CREATE_CATEGORIES:         'CREATE_CATEGORIES',
  UPDATE_CATEGORIES:         'UPDATE_CATEGORIES',
  DELETE_CATEGORIES:         'DELETE_CATEGORIES',
  CHANGE_STATUS_CATEGORIES:  'CHANGE_STATUS_CATEGORIES',

  // CLIENTS
  READ_CLIENTS:           'READ_CLIENTS',
  CREATE_CLIENTS:         'CREATE_CLIENTS',
  UPDATE_CLIENTS:         'UPDATE_CLIENTS',
  DELETE_CLIENTS:         'DELETE_CLIENTS',
  CHANGE_STATUS_CLIENTS:  'CHANGE_STATUS_CLIENTS',

  // INVENTORY
  READ_INVENTORY:     'READ_INVENTORY',
  CREATE_INVENTORY:   'CREATE_INVENTORY',
  UPDATE_INVENTORY:   'UPDATE_INVENTORY',
  DELETE_INVENTORY:   'DELETE_INVENTORY',
  CONFIRM_INVENTORY:  'CONFIRM_INVENTORY',
  CANCEL_INVENTORY:   'CANCEL_INVENTORY',

  // PERMISSIONS
  READ_PERMISSIONS:    'READ_PERMISSIONS',
  CREATE_PERMISSIONS:  'CREATE_PERMISSIONS',
  UPDATE_PERMISSIONS:  'UPDATE_PERMISSIONS',
  DELETE_PERMISSIONS:  'DELETE_PERMISSIONS',
  WRITER_PERMISSION:   'WRITER_PERMISSION',

  // PRODUCTS
  READ_PRODUCTS:           'READ_PRODUCTS',
  WRITE_PRODUCTS:          'WRITE_PRODUCTS',
  CREATE_PRODUCTS:         'CREATE_PRODUCTS',
  UPDATE_PRODUCTS:         'UPDATE_PRODUCTS',
  DELETE_PRODUCTS:         'DELETE_PRODUCTS',
  CHANGE_STATUS_PRODUCTS:  'CHANGE_STATUS_PRODUCTS',

  // PROVIDERS
  READ_PROVIDERS:           'READ_PROVIDERS',
  CREATE_PROVIDERS:         'CREATE_PROVIDERS',
  UPDATE_PROVIDERS:         'UPDATE_PROVIDERS',
  DELETE_PROVIDERS:         'DELETE_PROVIDERS',
  CHANGE_STATUS_PROVIDERS:  'CHANGE_STATUS_PROVIDERS',

  // ROLES
  READ_ROLES:              'READ_ROLES',
  CREATE_ROLES:            'CREATE_ROLES',
  UPDATE_ROLES:            'UPDATE_ROLES',
  DELETE_ROLES:            'DELETE_ROLES',
  ASSIGN_PERMISSION_ROLES: 'ASSIGN_PERMISSION_ROLES',

  // SALES
  READ_SALES:       'READ_SALES',
  CREATE_SALES:     'CREATE_SALES',
  UPDATE_SALES:     'UPDATE_SALES',
  DELETE_SALES:     'DELETE_SALES',
  CONFIRM_SALES:    'CONFIRM_SALES',
  CANCEL_SALES:     'CANCEL_SALES',
  MANAGE_CART_SALES: 'MANAGE_CART_SALES',

  // USERS
  READ_USERS:         'READ_USERS',
  CREATE_USERS:       'CREATE_USERS',
  UPDATE_USERS:       'UPDATE_USERS',
  DELETE_USERS:       'DELETE_USERS',
  CHANGE_STATUS_USERS: 'CHANGE_STATUS_USERS',
  ASSIGN_ROLE_USERS:  'ASSIGN_ROLE_USERS',
  MANAGE_USERS:       'MANAGE_USERS',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/** Permissions grouped by module — useful for building UI selectors. */
export const MODULE_PERMISSIONS: Record<string, readonly Permission[]> = {
  BRANDS:      [PERMISSIONS.READ_BRANDS, PERMISSIONS.CREATE_BRANDS, PERMISSIONS.UPDATE_BRANDS, PERMISSIONS.DELETE_BRANDS, PERMISSIONS.CHANGE_STATUS_BRANDS],
  CATEGORIES:  [PERMISSIONS.READ_CATEGORIES, PERMISSIONS.CREATE_CATEGORIES, PERMISSIONS.UPDATE_CATEGORIES, PERMISSIONS.DELETE_CATEGORIES, PERMISSIONS.CHANGE_STATUS_CATEGORIES],
  CLIENTS:     [PERMISSIONS.READ_CLIENTS, PERMISSIONS.CREATE_CLIENTS, PERMISSIONS.UPDATE_CLIENTS, PERMISSIONS.DELETE_CLIENTS, PERMISSIONS.CHANGE_STATUS_CLIENTS],
  INVENTORY:   [PERMISSIONS.READ_INVENTORY, PERMISSIONS.CREATE_INVENTORY, PERMISSIONS.UPDATE_INVENTORY, PERMISSIONS.DELETE_INVENTORY, PERMISSIONS.CONFIRM_INVENTORY, PERMISSIONS.CANCEL_INVENTORY],
  PERMISSIONS: [PERMISSIONS.READ_PERMISSIONS, PERMISSIONS.CREATE_PERMISSIONS, PERMISSIONS.UPDATE_PERMISSIONS, PERMISSIONS.DELETE_PERMISSIONS, PERMISSIONS.WRITER_PERMISSION],
  PRODUCTS:    [PERMISSIONS.READ_PRODUCTS, PERMISSIONS.WRITE_PRODUCTS, PERMISSIONS.CREATE_PRODUCTS, PERMISSIONS.UPDATE_PRODUCTS, PERMISSIONS.DELETE_PRODUCTS, PERMISSIONS.CHANGE_STATUS_PRODUCTS],
  PROVIDERS:   [PERMISSIONS.READ_PROVIDERS, PERMISSIONS.CREATE_PROVIDERS, PERMISSIONS.UPDATE_PROVIDERS, PERMISSIONS.DELETE_PROVIDERS, PERMISSIONS.CHANGE_STATUS_PROVIDERS],
  ROLES:       [PERMISSIONS.READ_ROLES, PERMISSIONS.CREATE_ROLES, PERMISSIONS.UPDATE_ROLES, PERMISSIONS.DELETE_ROLES, PERMISSIONS.ASSIGN_PERMISSION_ROLES],
  SALES:       [PERMISSIONS.READ_SALES, PERMISSIONS.CREATE_SALES, PERMISSIONS.UPDATE_SALES, PERMISSIONS.DELETE_SALES, PERMISSIONS.CONFIRM_SALES, PERMISSIONS.CANCEL_SALES, PERMISSIONS.MANAGE_CART_SALES],
  USERS:       [PERMISSIONS.READ_USERS, PERMISSIONS.CREATE_USERS, PERMISSIONS.UPDATE_USERS, PERMISSIONS.DELETE_USERS, PERMISSIONS.CHANGE_STATUS_USERS, PERMISSIONS.ASSIGN_ROLE_USERS, PERMISSIONS.MANAGE_USERS],
};
